version: '1.0'

services:
  langchainnotes:
    build:
      context: .
      dockerfile: ./Dockerfile
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
