version: '1.0'
services:
  langchainnotes:
    container_name: langchainnotes
    user: nonroot
    volumes:
    - ./:/home/nonroot/workspace
    tty: true

  ollama:
    image: ollama/ollama:latest
    volumes:
    - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
    - 11435:11434
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
