version: '1.0'
services:
  langchainnotes:
    container_name: langchainnotes-dev
    # image: python:3.11
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ../:/workspace:cached
    tty: true
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
